[package]
name = "rtk-glium"
version = "0.1.0"
authors = ["wolfiestyle <slayerbeast@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.27.0"
font-kit = "0.10.0"
glyph_brush = "0.7.0"
rtk = { path = "../core" }
rtk-winit = { path = "../backend-winit" }
