[package]
name = "widgets-glium"
version = "0.1.0"
authors = ["wolfiestyle <slayerbeast@gmail.com>"]
edition = "2018"

[dependencies]
glium = "0.27.0"
widgets = { path = "../core" }
widgets-winit = { path = "../backend-winit" }
