[package]
name = "rtk-derive"
version = "0.1.0"
authors = ["wolfiestyle <slayerbeast@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.32"
quote = "1.0.7"
proc-macro2 = "1.0.18"

[dev-dependencies]
rtk = { path = "../core" }
rtk-widgets = { path = "../widgets" }
