[package]
name = "rtk"
version = "0.1.0"
authors = ["wolfiestyle <slayerbeast@gmail.com>"]
edition = "2018"

[features]
default = ["image"]

[dependencies]
num-traits = "0.2.11"
font-kit = "0.10.0"
glyph_brush = "0.7.0"
image = { version = "0.23.5", optional = true }
