[package]
name = "widgets"
version = "0.1.0"
authors = ["wolfiestyle <slayerbeast@gmail.com>"]
edition = "2018"

[features]
default = ["image"]

[dependencies]
num-traits = "0.2.11"
image = { version = "0.23.5", optional = true }
