[package]
name = "testapp"
version = "0.1.0"
authors = ["wolfiestyle <slayerbeast@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
rtk = { path = "../core" }
rtk-glium = { path = "../backend-glium" }
rtk-derive = { path = "../proc-macros" }
