[package]
name = "testapp"
version = "0.1.0"
authors = ["wolfiestyle <slayerbeast@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
widgets = { path = "../core" }
widgets-glium = { path = "../backend-glium" }
widgets-derive = { path = "../proc-macros" }
